pipeline {
    agent any

    environment {
        DOCKERHUB_CREDENTIALS = credentials('dockerhub-id') // DockerHub login stored in Jenkins
        DOCKERHUB_USERNAME = 'your-dockerhub-username'
        BACKEND_IMAGE = "${DOCKERHUB_USERNAME}/backend-app:latest"
        FRONTEND_IMAGE = "${DOCKERHUB_USERNAME}/frontend-app:latest"
    }

    stages {
        stage('Clone Repository') {
            steps {
                git branch: 'main', url: 'https://github.com/<your-github-username>/cloud-native-cicd.git'
            }
        }

        stage('Build Backend Docker Image') {
            steps {
                dir('backend') {
                    sh 'docker build -t $BACKEND_IMAGE .'
                }
            }
        }

        stage('Build Frontend Docker Image') {
            steps {
                dir('frontend') {
                    sh 'docker build -t $FRONTEND_IMAGE .'
                }
            }
        }

        stage('Push Docker Images') {
            steps {
                sh 'docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_CREDENTIALS'
                sh 'docker push $BACKEND_IMAGE'
                sh 'docker push $FRONTEND_IMAGE'
            }
        }

        stage('Deploy to Kubernetes') {
            steps {
                sh 'kubectl apply -f k8s/backend-deployment.yaml'
             sh 'kubectl apply -f k8s/frontend-deployment.yaml'
            }
        }
    }
}


